import { useState, useEffect } from 'react';
import { apiService } from '../services/apiService';

function formatLeaveDate(dateVal) {
  if (!dateVal) return 'N/A';
  const d = new Date(dateVal);
  if (Number.isNaN(d.getTime())) return 'N/A';
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' });
}

function formatLeaveRange(startVal, endVal) {
  const start = formatLeaveDate(startVal);
  const end = formatLeaveDate(endVal);
  if (start === 'N/A' && end === 'N/A') return 'N/A';
  if (start === end) return start;
  return `${start} - ${end}`;
}

// Map leave type name to badge class (match existing UI: Emergency=danger, Casual=warning)
function getBadgeClass(leaveTypeName) {
  if (!leaveTypeName) return 'badge-soft-primary';
  const t = String(leaveTypeName).toLowerCase();
  if (t.includes('emergency')) return 'badge-soft-danger';
  if (t.includes('casual')) return 'badge-soft-warning';
  return 'badge-soft-primary';
}

export const useLeaveApplications = (options = {}) => {
  const {
    limit = 20,
    studentOnly = false,
    includeAutoGenerated = false,
    parentChildren = false,
    studentId = null,
    staffId = null,
    canUseAdminList = false,
    classId = null,
    sectionId = null,
    departmentId = null,
    designationId = null,
    academicYearId = null,
    leaveFrom = null,
    leaveTo = null,
    pendingOnly = false,
    status = null,
    leaveTypeId = null,
    applicantType = null,
    sortBy = null,
    sortOrder = null,
    page = null,
    pageSize = null,
    enabled = true,
  } = options;
  const [list, setList] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const shouldRetryWithoutAcademicYear =
    !pendingOnly && academicYearId != null;

  const buildAdminParams = (withAcademicYear = true, refreshKey = null) => ({
    limit,
    page: page ?? undefined,
    page_size: pageSize ?? undefined,
    academic_year_id: withAcademicYear ? academicYearId : undefined,
    leave_type_id: leaveTypeId ?? undefined,
    applicant_type: applicantType ?? undefined,
    class_id: classId ?? undefined,
    section_id: sectionId ?? undefined,
    department_id: departmentId ?? undefined,
    designation_id: designationId ?? undefined,
    status: status ?? undefined,
    sort_by: sortBy ?? undefined,
    sort_order: sortOrder ?? undefined,
    leave_from: leaveFrom || undefined,
    leave_to: leaveTo || undefined,
    ...(pendingOnly ? { pending_only: true } : {}),
    ...(refreshKey != null ? { _refresh: refreshKey } : {}),
  });

  const fetchList = async (bustCache = false) => {
    if (!enabled) {
      setList([]);
      setError(null);
      setLoading(false);
      return;
    }
    try {
      setLoading(true);
      setError(null);
      const refreshKey = bustCache ? Date.now() : null;
      let response;
      if (parentChildren) {
        response = await apiService.getParentChildrenLeaves({
          limit,
          student_id: studentId != null ? studentId : undefined,
        });
      } else if (studentOnly) {
        response = await apiService.getMyLeaveApplications({
          limit,
          academicYearId,
          includeAutoGenerated: includeAutoGenerated || undefined,
        });
      } else if (studentId != null) {
        // Admin-only endpoint - only call when role is confirmed (avoids 403 when role loading)
        if (!canUseAdminList) {
          setList([]);
          setLoading(false);
          return;
        }
        response = await apiService.getLeaveApplications({
          limit,
          page: page ?? undefined,
          page_size: pageSize ?? undefined,
          student_id: studentId,
          academic_year_id: academicYearId,
          leave_type_id: leaveTypeId ?? undefined,
          applicant_type: applicantType ?? undefined,
          class_id: classId ?? undefined,
          section_id: sectionId ?? undefined,
          department_id: departmentId ?? undefined,
          designation_id: designationId ?? undefined,
          status: status ?? undefined,
          sort_by: sortBy ?? undefined,
          sort_order: sortOrder ?? undefined,
          leave_from: leaveFrom || undefined,
          leave_to: leaveTo || undefined,
          ...(refreshKey != null ? { _refresh: refreshKey } : {}),
        });
      } else if (staffId != null) {
        if (!canUseAdminList) {
          setList([]);
          setLoading(false);
          return;
        }
        response = await apiService.getLeaveApplications({
          limit,
          page: page ?? undefined,
          page_size: pageSize ?? undefined,
          staff_id: staffId,
          academic_year_id: academicYearId,
          leave_type_id: leaveTypeId ?? undefined,
          applicant_type: applicantType ?? undefined,
          class_id: classId ?? undefined,
          section_id: sectionId ?? undefined,
          department_id: departmentId ?? undefined,
          designation_id: designationId ?? undefined,
          status: status ?? undefined,
          sort_by: sortBy ?? undefined,
          sort_order: sortOrder ?? undefined,
          leave_from: leaveFrom || undefined,
          leave_to: leaveTo || undefined,
          ...(refreshKey != null ? { _refresh: refreshKey } : {}),
        });
      } else if (canUseAdminList) {
        response = await apiService.getLeaveApplications(buildAdminParams(true, refreshKey));
      } else {
        // Role loading or non-admin - skip admin API to avoid 403
        setList([]);
        setLoading(false);
        return;
      }

      const rawData = response?.data;
      const dataArr = Array.isArray(rawData) ? rawData : (Array.isArray(rawData?.data) ? rawData.data : rawData?.items) || [];
      if (
        canUseAdminList &&
        shouldRetryWithoutAcademicYear &&
        Array.isArray(dataArr) &&
        dataArr.length === 0
      ) {
        const retryResponse = await apiService.getLeaveApplications(buildAdminParams(false, refreshKey));
        response = retryResponse;
      }
      const normalizedRawData = response?.data;
      const normalizedDataArr = Array.isArray(normalizedRawData)
        ? normalizedRawData
        : (Array.isArray(normalizedRawData?.data) ? normalizedRawData.data : normalizedRawData?.items) || [];
      const isSuccess =
        response &&
        (response.status === 'SUCCESS' || response.success === true);
      if (isSuccess && Array.isArray(normalizedDataArr)) {
        let rows = normalizedDataArr;
        if (!parentChildren && !studentOnly) {
          rows = rows.filter((r, i, a) => {
            if (r == null) return false;
            if (r.id == null) return true;
            return a.findIndex((x) => x && x.id === r.id) === i;
          });
        }
        // Safety: when viewing a specific staff's leaves, filter to only that staff_id
        if (!parentChildren && !studentOnly && staffId != null) {
          rows = rows.filter((r) => r.staff_id != null && Number(r.staff_id) === Number(staffId));
        }
        const mapped = await Promise.all(rows.map(async (row, index) => {
          const name =
            [row.applicant_first_name, row.applicant_last_name].filter(Boolean).join(' ') ||
            [row.staff_first_name, row.staff_last_name].filter(Boolean).join(' ') ||
            row.applicant_name ||
            'N/A';
          const leaveType =
            row.leave_type_name || row.leave_type || row.type_name || 'N/A';
          const role =
            row.applicant_role ||
            row.designation_name ||
            row.designation ||
            row.role ||
            'N/A';
          const startDate = row.start_date || row.from_date;
          const endDate = row.end_date || row.to_date;
          const appliedAt = row.applied_at || row.created_at || row.start_date;
          const leaveRange = formatLeaveRange(startDate, endDate);
          const appliedOn = formatLeaveDate(appliedAt);
          const photoRaw =
            row.applicant_photo_url ||
            row.staff_photo_url ||
            row.photo_url ||
            '';
          const photoUrl = (photoRaw ? await apiService.resolveAvatarUrl(photoRaw) : '') || 'assets/img/profiles/avatar-27.jpg';

          const statusRaw = row.status || row.leave_status || 'pending';
          const statusLower = String(statusRaw).toLowerCase();
          let statusVal = statusLower;
          if (['accept', 'accepted', 'approved'].includes(statusVal) || (statusVal.includes('approv') && !statusVal.includes('reject'))) {
            statusVal = 'approved';
          } else if (['rejected', 'decline', 'declined', 'deny', 'denied'].includes(statusVal) || (statusVal.includes('reject') && !statusVal.includes('approv'))) {
            statusVal = 'rejected';
          } else if (statusVal === 'auto-generated' || statusVal === 'auto generated') {
            statusVal = 'auto-generated';
          }
          const approvedByName = String(row.approved_by_name || "").trim();
          const approvedBy =
            approvedByName ||
            (row.approved_by != null && String(row.approved_by).trim() !== "" ? `Staff #${row.approved_by}` : null);

          const noOfDays = row.total_days ?? row.no_of_days ?? row.noOfDays ?? (startDate && endDate ? Math.ceil((new Date(endDate) - new Date(startDate)) / (24 * 60 * 60 * 1000)) + 1 : 1);

          return {
            key: row.id != null ? String(row.id) : `leave-${index}`,
            id: row.id,
            leaveTypeId: row.leave_type_id ?? row.leaveTypeId ?? null,
            studentId: row.student_id ?? null,
            staffId: row.staff_id ?? row.applicant_staff_id ?? null,
            applicantType:
              row.applicant_type ||
              (row.student_id != null ? 'student' : row.staff_id != null || row.applicant_staff_id != null ? 'staff' : null),
            name,
            leaveType,
            role,
            leaveRange,
            leaveDate: leaveRange,
            startDate,
            endDate,
            noOfDays: String(noOfDays),
            appliedOn,
            applyOn: appliedOn,
            photoUrl,
            description:
              row.reason ||
              row.description ||
              row.leave_reason ||
              row.leaveDescription ||
              '',
            badgeClass: getBadgeClass(leaveType),
            status: statusVal,
            rejectionReason: row.rejection_reason ?? null,
            document_url: row.document_url || null,
            approvedBy,
            approvedDate: row.approved_date ?? null,
            statusBadgeClass:
              statusVal === 'approved'
                ? 'bg-success'
                : statusVal === 'rejected' || statusLower.includes('declin') || statusLower.includes('reject')
                ? 'bg-danger'
                : statusVal === 'auto-generated'
                ? 'bg-secondary'
                : 'bg-skyblue',
          };
        }));
        setList(mapped);
      } else {
        setList([]);
        const errMsg = response?.message || response?.error;
        if (errMsg) setError(String(errMsg));
      }
    } catch (err) {
      console.error('Error fetching leave applications:', err);
      setError(err.message || 'Failed to fetch leave applications');
      setList([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchList(false);
  }, [limit, studentOnly, includeAutoGenerated, parentChildren, studentId, staffId, canUseAdminList, classId, sectionId, departmentId, designationId, academicYearId, leaveFrom, leaveTo, pendingOnly, status, leaveTypeId, applicantType, sortBy, sortOrder, page, pageSize, enabled]);

  return {
    leaveApplications: list,
    loading,
    error,
    refetch: () => fetchList(true),
  };
};
