-- ============================================================================
-- Migration: create leaving_students workflow table
-- Purpose:
--   - Store school-leaving/withdrawal records from Student Promotion module
--   - Keep join + leave snapshots for audit/history
--   - Track final class result (Pass/Fail/Not Available) before leaving
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.leaving_students (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
  admission_number VARCHAR(20),
  student_first_name VARCHAR(50),
  student_last_name VARCHAR(50),

  joining_class_id INTEGER REFERENCES public.classes(id) ON DELETE SET NULL,
  joining_section_id INTEGER REFERENCES public.sections(id) ON DELETE SET NULL,
  joining_academic_year_id INTEGER REFERENCES public.academic_years(id) ON DELETE SET NULL,
  joining_date DATE,

  last_class_id INTEGER REFERENCES public.classes(id) ON DELETE SET NULL,
  last_section_id INTEGER REFERENCES public.sections(id) ON DELETE SET NULL,
  last_academic_year_id INTEGER REFERENCES public.academic_years(id) ON DELETE SET NULL,
  leaving_date DATE NOT NULL DEFAULT CURRENT_DATE,

  last_class_result VARCHAR(20) NOT NULL DEFAULT 'Not Available'
    CHECK (last_class_result IN ('Pass', 'Fail', 'Not Available')),
  reason TEXT,
  remarks TEXT,

  left_by INTEGER REFERENCES public.staff(id) ON DELETE SET NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by INTEGER,
  modified_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_leaving_students_student_id
  ON public.leaving_students(student_id);

CREATE INDEX IF NOT EXISTS idx_leaving_students_leaving_date
  ON public.leaving_students(leaving_date DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_leaving_students_student_active_leave
  ON public.leaving_students(student_id)
  WHERE is_active = TRUE;

