-- ============================================================================
-- Migration: 046_create_student_rejoins
-- Purpose:
--   - Persist audit history whenever a previously-left student is rejoined.
--   - Keep source (leaving snapshot) and target (rejoin destination) in one row.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.student_rejoins (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES public.students(id) ON DELETE RESTRICT,
  leaving_student_id INTEGER REFERENCES public.leaving_students(id) ON DELETE SET NULL,

  admission_number VARCHAR(20),
  student_first_name VARCHAR(50),
  student_last_name VARCHAR(50),

  from_class_id INTEGER REFERENCES public.classes(id) ON DELETE SET NULL,
  from_section_id INTEGER REFERENCES public.sections(id) ON DELETE SET NULL,
  from_academic_year_id INTEGER REFERENCES public.academic_years(id) ON DELETE SET NULL,
  leaving_date DATE,

  to_class_id INTEGER NOT NULL REFERENCES public.classes(id) ON DELETE RESTRICT,
  to_section_id INTEGER NOT NULL REFERENCES public.sections(id) ON DELETE RESTRICT,
  to_academic_year_id INTEGER NOT NULL REFERENCES public.academic_years(id) ON DELETE RESTRICT,
  rejoin_date DATE NOT NULL DEFAULT CURRENT_DATE,

  reason TEXT,
  remarks TEXT,
  rejoined_by INTEGER REFERENCES public.staff(id) ON DELETE SET NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by INTEGER,
  modified_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_student_rejoins_student_id
  ON public.student_rejoins(student_id);

CREATE INDEX IF NOT EXISTS idx_student_rejoins_rejoin_date
  ON public.student_rejoins(rejoin_date DESC);

CREATE INDEX IF NOT EXISTS idx_student_rejoins_to_academic_year_id
  ON public.student_rejoins(to_academic_year_id);
